name: Template Documentation Pipeline
description: Pipeline for generating and publishing documentation from Harness templates
type: pipeline
author: Harness Team
version: 1.0.0
tags:
  - documentation
  - confluence
  - templates

pipeline:
  name: Template Documentation
  identifier: template_documentation
  projectIdentifier: <+project.identifier>
  orgIdentifier: <+org.identifier>
  tags: {}
  variables:
    docker_registry_connector:
      type: string
      description: Connector ID for Docker registry
      required: true
    git_connector:
      type: string
      description: Connector ID for Git repository
      required: true
    repo_name:
      type: string
      description: Name of the repository containing Harness templates
      required: true
    image_name:
      type: string
      description: Docker image name for documentation generator
      required: true
      default: harness-template-docs:latest
    source_dir:
      type: string
      description: Source directory containing templates
      required: false
      default: templates
    output_dir:
      type: string
      description: Output directory for generated documentation
      required: false
      default: docs/templates
    publish_to_confluence:
      type: boolean
      description: Whether to publish documentation to Confluence
      required: false
      default: false

  stages:
    - stage:
        name: Generate and Publish Documentation
        identifier: generate_and_publish_documentation
        template:
          name: Documentation Generator Stage
          identifier: docs_generator_stage
          versionLabel: 1.0.0
        variables:
          docker_registry_connector: <+pipeline.variables.docker_registry_connector>
          image_name: <+pipeline.variables.image_name>
          source_dir: <+pipeline.variables.source_dir>
          output_dir: <+pipeline.variables.output_dir>
          publish_to_confluence: <+pipeline.variables.publish_to_confluence>
          confluence_url_secret: <+pipeline.variables.publish_to_confluence == true ? "confluence_url" : null>
          confluence_username_secret: <+pipeline.variables.publish_to_confluence == true ? "confluence_username" : null>
          confluence_token_secret: <+pipeline.variables.publish_to_confluence == true ? "confluence_token" : null>
          confluence_space_secret: <+pipeline.variables.publish_to_confluence == true ? "confluence_space" : null>
          confluence_parent_id_secret: <+pipeline.variables.publish_to_confluence == true ? "confluence_parent_id" : null>
          
  properties:
    ci:
      codebase:
        connectorRef: <+pipeline.variables.git_connector>
        repoName: <+pipeline.variables.repo_name>
        build: <+input>

examples:
  - |
    # Basic usage without Confluence publishing
    pipeline:
      name: Generate Template Documentation
      identifier: generate_template_documentation
      variables:
        docker_registry_connector: docker_hub
        git_connector: github_connector
        repo_name: my-templates-repo
        image_name: harness-template-docs:latest
        publish_to_confluence: false
  - |
    # Complete usage with Confluence publishing
    pipeline:
      name: Generate and Publish Template Documentation
      identifier: generate_and_publish_template_documentation
      variables:
        docker_registry_connector: docker_hub
        git_connector: github_connector
        repo_name: my-templates-repo
        image_name: harness-template-docs:latest
        source_dir: templates
        output_dir: docs/templates
        publish_to_confluence: true 