name: Example CI Pipeline
description: A standard CI pipeline template for building and testing applications
type: pipeline
author: Harness Team
version: 1.0.0
tags:
  - CI
  - build
  - test

pipeline:
  variables:
    buildNumber:
      type: string
      description: The build number for this pipeline run
      required: true
    environment:
      type: string
      description: The environment to deploy to
      required: false

  parameters:
    language:
      type: string
      description: Programming language of the application
      default: java
      required: true
    buildTool:
      type: string
      description: Build tool to use
      default: maven
      required: false

  stages:
    - name: Build
      description: Build the application
    - name: Test
      description: Run tests on the application
    - name: Deploy
      description: Deploy the application

examples:
  - |
    # Example usage in harness.yaml
    pipeline:
      template:
        name: Example CI Pipeline
        identifier: example_ci_pipeline
        versionLabel: 1.0.0
      variables:
        buildNumber: ${workflow.sequenceId}
        environment: dev
      parameters:
        language: java
        buildTool: gradle
